
services:
  app:
    build:
      context: /.
      dockerfile: Dockerfile
    ports:
      - "8005:8005"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/warehouse
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root123
    depends_on:
      - db

  db:
    image: postgres:17
    container_name: postgres_container
    environment:
      POSTGRES_DB: warehouse
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root123
    ports:
      - "5432:5432"
